name: license-check
on:
  push:
    paths:
      - 'vendor'
  pull_request:
    paths:
      - 'vendor'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@master

      - name: Setup Go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
          cache-dependency-path: "**/*.sum"
          go-version-file: 'qubership-apihub-service/go.mod'

      - name: Check License
        run: |
          go get -t github.com/Netcracker/qubership-apihub-backend/qubership-apihub-service
          go mod vendor | grep "go get" | awk '{print $3}' | xargs -n1 go get
          go mod vendor
          which wwhrd || go install github.com/frapposelli/wwhrd@latest
          wwhrd check -f .wwhrd.yml
        working-directory: ${{ github.workspace }}/qubership-apihub-service
