name: license-check
on:
  push:
    paths:
      - 'vendor'
  pull_request:
    paths:
      - 'vendor'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@master

      - name: Setup Go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false

      - name: Cache Go artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
          key: go-artifacts-${{ runner.os }}-check-licenses-${{ steps.go.outputs.go-version }}
          restore-keys: go-artifacts-${{ runner.os }}-check-licenses-

      - name: Check License
        run: |
          go get -t github.com/Netcracker/qubership-apihub-backend/qubership-apihub-service/service
          go mod vendor | grep "go get" | awk '{print $3}' | xargs -n1 go get
          go mod vendor
          which wwhrd || go install github.com/frapposelli/wwhrd@latest
          wwhrd check -f .wwhrd.yml
        working-directory: ${{ github.workspace }}/qubership-apihub-service